[package]
name = "common-tcp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
socks = "0.3.4"
base64 = "0.22.1"
httparse = "1.10.1"
native-tls = "0.2.14"
serde_json = "1.0"
url = "2.5.4"
